version: '3.8'

services:
  mariadb:
    image: mariadb:10.9
    container_name: testvault_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testvault
      MYSQL_USER: testvault
      MYSQL_PASSWORD: initialpass123
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - vault_network

  vault:
    image: hashicorp/vault:1.15
    container_name: vault_server
    restart: unless-stopped
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: myroot
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    ports:
      - "8200:8200"
    volumes:
      - vault_data:/vault/data
      - ./vault/config:/vault/config
    command: vault server -dev -dev-root-token-id=myroot
    networks:
      - vault_network

volumes:
  mariadb_data:
  vault_data:

networks:
  vault_network:
    driver: bridge 